### ISSUE TITLE
CLI Install

### ISSUE THREAD

**Issue by lander2k2** [arctir/proctor#28]
Had a couple of problems installing the proctor CLI...

The [install guide](https://github.com/arctir/proctor#install) has a link to github releases, but there aren't any released packages yet.

For the install with go I got the following results:
```
go install github.com/arctir/proctor
go: 'go install' requires a version when current directory is not in a module
        Try 'go install github.com/arctir/proctor@latest' to install the latest version
```
then...
```
go install github.com/arctir/proctor@latest
go: downloading github.com/arctir/proctor v0.0.0-20221223155144-1ddcb6c0b77d
go: github.com/arctir/proctor@latest: module github.com/arctir/proctor@latest found (v0.0.0-20221223155144-1ddcb6c0b77d), but does not contain package github.com/arctir/proctor
```
I think that last one is b/c the package inside the proctor director is `main`.

In case it's relevant:
```
go version
go version go1.19.4 linux/amd64
```

**Comment by joshrosso** [comment]
@lander2k2 thanks for opening this up. Since this is a "sorta" mono-repo -- the command is pointing the wrong place.

To install, the command would be:

```
go install github.com/arctir/proctor/proctor@latest
```

Fixed in: https://github.com/arctir/proctor/pull/29

If this doesn't work for you, give me a shout!

**Comment by joshrosso** [comment]
Note to future reader, the path `proctor/proctor` is pretty awkward, but I foresee this being temporary once we break thing out more thoughtfully.

**Comment by lander2k2** [comment]
That did the trick.  All set now :+1:
